name: Build README

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Update README
        env:
          YAFYX_TOKEN: ${{ secrets.YAFYX_TOKEN }}
        run: |-
          python update_readme.py
          cat README.md
      - name: Commit and push if changed
        run: |-
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated README" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
