name: Build README

on:
  push:
  schedule:
    - cron: "8,28,48 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Update README
        id: update
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          YAFYX_TOKEN: ${{ secrets.YAFYX_TOKEN }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        run: |-
          python update_readme.py
          cat README.md
      - name: Get script output
        id: script_output
        run: echo "::set-output name=tracks_changed::$(python update_readme.py | grep TRACKS_CHANGED | cut -d'=' -f2)"
      - name: Commit and push if changed
        if: steps.script_output.outputs.tracks_changed == 'true'
        run: |-
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated README" && git push)
